# Generated by Django 4.2.16 on 2025-11-25 16:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название темы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('difficulty_base', models.IntegerField(default=1000, help_text='Средний уровень сложности задач в этой теме', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Базовая сложность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок задачи')),
                ('latex_formula', models.TextField(help_text='Математическая формула в формате LaTeX', verbose_name='Формула (LaTeX)')),
                ('description', models.TextField(help_text='Текстовое описание задачи', verbose_name='Описание задачи')),
                ('correct_answer', models.CharField(max_length=200, verbose_name='Правильный ответ')),
                ('difficulty_score', models.IntegerField(help_text='Уровень сложности задачи (0-3000)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Сложность')),
                ('solution_steps', models.JSONField(default=list, help_text='Детальное пошаговое решение в формате JSON', verbose_name='Шаги решения')),
                ('hints', models.JSONField(blank=True, default=list, help_text='Список подсказок для решения', verbose_name='Подсказки')),
                ('is_active', models.BooleanField(default=True, help_text='Доступна ли задача для генерации', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.topic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['difficulty_score', 'topic'],
            },
        ),
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_answer', models.CharField(max_length=200, verbose_name='Ответ пользователя')),
                ('is_correct', models.BooleanField(verbose_name='Правильно')),
                ('attempt_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата попытки')),
                ('points_awarded', models.IntegerField(default=0, verbose_name='Начислено очков')),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True, verbose_name='Время решения (сек)')),
                ('solution_photo', models.ImageField(blank=True, null=True, upload_to='solutions/%Y/%m/%d/', verbose_name='Фото решения')),
                ('ai_analysis', models.JSONField(blank=True, help_text='Результат анализа решения ИИ', null=True, verbose_name='Анализ ИИ')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='problems.problem', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка решения',
                'verbose_name_plural': 'Попытки решений',
                'ordering': ['-attempt_date'],
                'indexes': [models.Index(fields=['user', '-attempt_date'], name='problems_us_user_id_f5a8c9_idx'), models.Index(fields=['problem', '-attempt_date'], name='problems_us_problem_074282_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty_score', 'is_active'], name='problems_pr_difficu_5c346c_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['topic', 'difficulty_score'], name='problems_pr_topic_i_32c402_idx'),
        ),
    ]
