# Generated by Django 4.2.16 on 2025-11-26 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userattempt',
            name='problem',
            field=models.ForeignKey(blank=True, help_text='Задача из БД (null для AI-генерируемых задач)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='problems.problem', verbose_name='Задача'),
        ),
    ]
