# Generated by Django 4.2.16 on 2025-12-27 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_userattempt_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='grade_level',
            field=models.IntegerField(blank=True, help_text='Для какого класса предназначена задача (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='problem',
            name='source',
            field=models.CharField(choices=[('ai_generated', 'AI сгенерирована'), ('manual', 'Создана вручную'), ('imported', 'Импортирована')], default='ai_generated', help_text='Источник задачи (ai_generated, manual, imported)', max_length=50, verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='problem',
            name='times_used',
            field=models.IntegerField(default=0, help_text='Сколько раз задача была показана пользователям', verbose_name='Использована раз'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['grade_level', 'difficulty_score', 'is_active'], name='problems_pr_grade_l_75e8b3_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_active', 'times_used'], name='problems_pr_is_acti_a8e726_idx'),
        ),
    ]
