# Generated by Django 4.2.16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_grade_level_problem_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='problems.topic', verbose_name='Тема'),
        ),
    ]
