# Generated by Django 4.2.16 on 2025-12-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_alter_problem_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-created_at'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_pr_difficu_5c346c_idx',
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_pr_grade_l_75e8b3_idx',
        ),
        migrations.RemoveIndex(
            model_name='problem',
            name='problems_pr_is_acti_a8e726_idx',
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['difficulty_score'], name='problems_pr_difficu_123ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['grade_level'], name='problems_pr_grade_l_b4a704_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['is_active'], name='problems_pr_is_acti_c99e79_idx'),
        ),
        migrations.AddIndex(
            model_name='problem',
            index=models.Index(fields=['source'], name='problems_pr_source_bdb435_idx'),
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['user', 'is_correct'], name='problems_us_user_id_3ff92e_idx'),
        ),
        migrations.AddIndex(
            model_name='userattempt',
            index=models.Index(fields=['user', 'problem'], name='problems_us_user_id_55e292_idx'),
        ),
    ]
