# Generated by Django 4.2.16 on 2025-11-25 15:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('RU', 'Россия'), ('KZ', 'Казахстан'), ('UZ', 'Узбекистан'), ('KG', 'Кыргызстан'), ('TJ', 'Таджикистан'), ('UA', 'Украина'), ('BY', 'Беларусь'), ('AZ', 'Азербайджан'), ('OTHER', 'Другая')], default='RU', max_length=10, verbose_name='Страна')),
                ('al_khwarizmi_index', models.IntegerField(default=1000, help_text='Рейтинг пользователя (0-3000)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Индекс Ал Хоразми')),
                ('total_solved_problems', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего решено задач')),
                ('total_arena_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего очков арены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-al_khwarizmi_index'],
            },
        ),
    ]
