# Generated by Django 4.2.16 on 2025-11-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс'), (12, '12 класс / Выпускник')], null=True, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Школа/Университет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Ученик'), ('teacher', 'Учитель'), ('university', 'Студент'), ('other', 'Другое')], default='student', max_length=20, verbose_name='Тип пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('RU', 'Россия'), ('KZ', 'Казахстан'), ('UZ', 'Узбекистан'), ('KG', 'Кыргызстан'), ('TJ', 'Таджикистан'), ('UA', 'Украина'), ('BY', 'Беларусь'), ('AZ', 'Азербайджан'), ('OTHER', 'Другая')], default='KZ', max_length=10, verbose_name='Страна'),
        ),
    ]
