# Generated by Django 4.2.16 on 2025-11-25 16:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_index', models.IntegerField(default=1000, help_text='Копия индекса из профиля для быстрого доступа', verbose_name='Текущий индекс')),
                ('current_division', models.CharField(choices=[('NOVICE', 'Лига Новичков'), ('EUCLID', 'Лига Евклида'), ('EINSTEIN', 'Лига Эйнштейна')], default='EUCLID', max_length=20, verbose_name='Текущий дивизион')),
                ('weekly_score', models.IntegerField(default=0, help_text='Очки, заработанные за текущую неделю', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Очки за неделю')),
                ('rank', models.IntegerField(default=0, help_text='Место в текущем дивизионе', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Место в рейтинге')),
                ('total_cups', models.IntegerField(default=0, help_text='Количество выигранных дивизионных кубков', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего кубков')),
                ('total_medals', models.IntegerField(default=0, help_text='Количество золотых медалей (топ-3)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Всего медалей')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='arena_rank', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Рейтинг арены',
                'verbose_name_plural': 'Рейтинги арены',
                'ordering': ['current_division', 'rank'],
                'indexes': [models.Index(fields=['current_division', 'rank'], name='arena_arena_current_1b575e_idx'), models.Index(fields=['current_division', '-weekly_score'], name='arena_arena_current_06962a_idx')],
            },
        ),
    ]
